In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

In [2]:
headers = ['Vendor name', 'Model name', 'MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN', 'CHMAX', 'PRP', 'ERP']

In [3]:
df = pd.read_csv('cpuperformance.csv', names = headers)
df

Vendor name     Model name  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  \
0       adviser          32/60   125   256   6000   256     16    128  198   
1        amdahl         470v/7    29  8000  32000    32      8     32  269   
2        amdahl        470v/7a    29  8000  32000    32      8     32  220   
3        amdahl        470v/7b    29  8000  32000    32      8     32  172   
4        amdahl        470v/7c    29  8000  16000    32      8     16  132   
..          ...            ...   ...   ...    ...   ...    ...    ...  ...   
204      sperry           80/8   124  1000   8000     0      1      8   42   
205      sperry  90/80-model-3    98  1000   8000    32      2      8   46   
206      sratus             32   125  2000   8000     0      2     14   52   
207        wang         vs-100   480   512   8000    32      0      0   67   
208        wang          vs-90   480  1000   4000     0      0      0   45   

     ERP  
0    199  
1    253  
2    253  
3    253  
4    132  
..   ...  
204   37  
205   50  
206   41  
207   47  
208   25  

[209 rows x 10 columns]

In [4]:
df.describe()

MYCT          MMIN          MMAX        CACH       CHMIN  \
count   209.000000    209.000000    209.000000  209.000000  209.000000   
mean    203.822967   2867.980861  11796.153110   25.205742    4.698565   
std     260.262926   3878.742758  11726.564377   40.628722    6.816274   
min      17.000000     64.000000     64.000000    0.000000    0.000000   
25%      50.000000    768.000000   4000.000000    0.000000    1.000000   
50%     110.000000   2000.000000   8000.000000    8.000000    2.000000   
75%     225.000000   4000.000000  16000.000000   32.000000    6.000000   
max    1500.000000  32000.000000  64000.000000  256.000000   52.000000   

            CHMAX          PRP          ERP  
count  209.000000   209.000000   209.000000  
mean    18.267943   105.622010    99.330144  
std     25.997318   160.830733   154.757102  
min      0.000000     6.000000    15.000000  
25%      5.000000    27.000000    28.000000  
50%      8.000000    50.000000    45.000000  
75%     24.000000   113.000000   101.000000  
max    176.000000  1150.000000  1238.000000

In [5]:
df.dtypes

Vendor name    object
Model name     object
MYCT            int64
MMIN            int64
MMAX            int64
CACH            int64
CHMIN           int64
CHMAX           int64
PRP             int64
ERP             int64
dtype: object

In [6]:
df['Model name'].unique()

array(['32/60', '470v/7', '470v/7a', '470v/7b', '470v/7c', '470v/b',
       '580-5840', '580-5850', '580-5860', '580-5880', 'dn320', 'dn420',
       '7/65', '7/68', '5000', '8000', 'b1955', 'b2900', 'b2925', 'b4955',
       'b5900', 'b5920', 'b6900', 'b6925', '68/10-80', 'universe:2203t',
       'universe:68', 'universe:68/05', 'universe:68/137',
       'universe:68/37', 'cyber:170/750', 'cyber:170/760',
       'cyber:170/815', 'cyber:170/825', 'cyber:170/835', 'cyber:170/845',
       'omega:480-i', 'omega:480-ii', 'omega:480-iii', '1636-1',
       '1636-10', '1641-1', '1641-11', '1651-1', 'decsys:10:1091',
       'decsys:20:2060', 'microvax-1', 'vax:11/730', 'vax:11/750',
       'vax:11/780', 'eclipse:c/350', 'eclipse:m/600', 'eclipse:mv/10000',
       'eclipse:mv/4000', 'eclipse:mv/6000', 'eclipse:mv/8000',
       'eclipse:mv/8000-ii', 'f4000/100', 'f4000/200', 'f4000/200ap',
       'f4000/300', 'f4000/300ap', '2000/260', 'concept:32/8705',
       'concept:32/8750', 'concept:32/8780'

In [7]:
df.corr()

MYCT      MMIN      MMAX      CACH     CHMIN     CHMAX       PRP  \
MYCT   1.000000 -0.335642 -0.378561 -0.321000 -0.301090 -0.250502 -0.307099   
MMIN  -0.335642  1.000000  0.758157  0.534729  0.517189  0.266907  0.794931   
MMAX  -0.378561  0.758157  1.000000  0.537990  0.560513  0.527246  0.863004   
CACH  -0.321000  0.534729  0.537990  1.000000  0.582245  0.487846  0.662641   
CHMIN -0.301090  0.517189  0.560513  0.582245  1.000000  0.548281  0.608903   
CHMAX -0.250502  0.266907  0.527246  0.487846  0.548281  1.000000  0.605209   
PRP   -0.307099  0.794931  0.863004  0.662641  0.608903  0.605209  1.000000   
ERP   -0.288396  0.819292  0.901202  0.648620  0.610580  0.592156  0.966472   

            ERP  
MYCT  -0.288396  
MMIN   0.819292  
MMAX   0.901202  
CACH   0.648620  
CHMIN  0.610580  
CHMAX  0.592156  
PRP    0.966472  
ERP    1.000000

In [8]:
df['Vendor name'].unique()

array(['adviser', 'amdahl', 'apollo', 'basf', 'bti', 'burroughs', 'c.r.d',
       'cdc', 'cambex', 'dec', 'dg', 'formation', 'four-phase', 'gould',
       'hp', 'harris', 'honeywell', 'ibm', 'ipl', 'magnuson', 'microdata',
       'nas', 'ncr', 'nixdorf', 'perkin-elmer', 'prime', 'siemens',
       'sperry', 'sratus', 'wang'], dtype=object)

In [9]:
"""
label_encoder = LabelEncoder()
x = ['adviser', 'amdahl', 'apollo', 'basf', 'bti', 'burroughs', 'c.r.d',
       'cdc', 'cambex', 'dec', 'dg', 'formation', 'four-phase', 'gould',
       'hp', 'harris', 'honeywell', 'ibm', 'ipl', 'magnuson', 'microdata',
       'nas', 'ncr', 'nixdorf', 'perkin-elmer', 'prime', 'siemens',
       'sperry', 'sratus', 'wang']
y = label_encoder.fit_transform(x)
print (y)
"""

"\nlabel_encoder = LabelEncoder()\nx = ['adviser', 'amdahl', 'apollo', 'basf', 'bti', 'burroughs', 'c.r.d',\n       'cdc', 'cambex', 'dec', 'dg', 'formation', 'four-phase', 'gould',\n       'hp', 'harris', 'honeywell', 'ibm', 'ipl', 'magnuson', 'microdata',\n       'nas', 'ncr', 'nixdorf', 'perkin-elmer', 'prime', 'siemens',\n       'sperry', 'sratus', 'wang']\ny = label_encoder.fit_transform(x)\nprint (y)\n"

In [10]:
enc = OneHotEncoder(handle_unknown='ignore')

In [11]:
enc_df = pd.DataFrame(enc.fit_transform(df[['Vendor name']]).toarray())

In [12]:
df = df.join(enc_df)
df

Vendor name     Model name  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  \
0       adviser          32/60   125   256   6000   256     16    128  198   
1        amdahl         470v/7    29  8000  32000    32      8     32  269   
2        amdahl        470v/7a    29  8000  32000    32      8     32  220   
3        amdahl        470v/7b    29  8000  32000    32      8     32  172   
4        amdahl        470v/7c    29  8000  16000    32      8     16  132   
..          ...            ...   ...   ...    ...   ...    ...    ...  ...   
204      sperry           80/8   124  1000   8000     0      1      8   42   
205      sperry  90/80-model-3    98  1000   8000    32      2      8   46   
206      sratus             32   125  2000   8000     0      2     14   52   
207        wang         vs-100   480   512   8000    32      0      0   67   
208        wang          vs-90   480  1000   4000     0      0      0   45   

     ERP  ...   20   21   22   23   24   25   26   27   28   29  
0    199  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    253  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    253  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    253  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    132  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
204   37  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
205   50  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
206   41  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
207   47  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
208   25  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  

[209 rows x 40 columns]

In [13]:
df.corr()

MYCT      MMIN      MMAX      CACH     CHMIN     CHMAX       PRP  \
MYCT   1.000000 -0.335642 -0.378561 -0.321000 -0.301090 -0.250502 -0.307099   
MMIN  -0.335642  1.000000  0.758157  0.534729  0.517189  0.266907  0.794931   
MMAX  -0.378561  0.758157  1.000000  0.537990  0.560513  0.527246  0.863004   
CACH  -0.321000  0.534729  0.537990  1.000000  0.582245  0.487846  0.662641   
CHMIN -0.301090  0.517189  0.560513  0.582245  1.000000  0.548281  0.608903   
CHMAX -0.250502  0.266907  0.527246  0.487846  0.548281  1.000000  0.605209   
PRP   -0.307099  0.794931  0.863004  0.662641  0.608903  0.605209  1.000000   
ERP   -0.288396  0.819292  0.901202  0.648620  0.610580  0.592156  0.966472   
0     -0.021050 -0.046805 -0.034354  0.394822  0.115238  0.293369  0.039922   
1     -0.145286  0.573734  0.463073  0.165822  0.269371  0.126860  0.410805   
2      0.074269 -0.053650 -0.071808 -0.056277 -0.053464 -0.054076 -0.040815   
3     -0.056342  0.003354  0.001713  0.096507 -0.053464 -0.038916  0.005745   
4      0.026946 -0.065539 -0.031628 -0.061128 -0.031781 -0.001016 -0.050924   
5     -0.050769 -0.038075 -0.118244 -0.031776  0.030848  0.154671 -0.069473   
6      0.076927 -0.113207 -0.107224 -0.095603 -0.093509 -0.082428 -0.067458   
7     -0.092751 -0.051302  0.002728 -0.066459 -0.039106 -0.077677 -0.061299   
8     -0.128401 -0.024194 -0.048407  0.104180  0.113391 -0.005827  0.032378   
9      0.130561 -0.093836 -0.071679 -0.080050 -0.076654 -0.078008 -0.062457   
10     0.077150 -0.099213 -0.055861 -0.073774 -0.101251 -0.117792 -0.059728   
11     0.359480 -0.105679 -0.050802 -0.097359 -0.085153 -0.086128 -0.086669   
12    -0.021050 -0.042217 -0.063989 -0.043120  0.033664  0.004631 -0.030088   
13    -0.059876 -0.027070  0.015857  0.179023 -0.065638  0.091815  0.057698   
14     0.056665 -0.107625 -0.080257 -0.096082 -0.023035  0.048321 -0.064866   
15     0.004601 -0.083369 -0.007366 -0.081955 -0.108031  0.142472 -0.072489   
16    -0.071365 -0.077715 -0.121785 -0.100019 -0.046500  0.031915 -0.080281   
17     0.393937  0.016128 -0.082307 -0.151976 -0.096440 -0.188832 -0.054402   
18    -0.101854  0.005866 -0.006802 -0.027737 -0.076654 -0.076904 -0.039241   
19    -0.085300 -0.060780  0.002996 -0.030564 -0.026089 -0.048178 -0.070672   
20    -0.014374 -0.042217 -0.046208 -0.043120  0.033664  0.293369 -0.032681   
21    -0.169784  0.204346  0.164854  0.232867  0.045837 -0.058457  0.140474   
22    -0.147085  0.049745 -0.041235  0.043171  0.008503 -0.053075 -0.067921   
23    -0.001777 -0.047861 -0.073545 -0.011530 -0.065638 -0.067941 -0.055374   
24     0.021463 -0.068404 -0.039160 -0.074055 -0.047891 -0.050880 -0.048103   
25    -0.026424 -0.075383 -0.088274 -0.051008 -0.075943 -0.045080 -0.050566   
26    -0.105583  0.088278  0.041221  0.057610  0.092605 -0.042201  0.024937   
27    -0.101610 -0.029366  0.241570  0.125285  0.323146  0.348714  0.239651   
28    -0.021050 -0.015554 -0.022500 -0.043120 -0.027517 -0.011410 -0.023173   
29     0.104555 -0.053650 -0.048701 -0.022325 -0.067919 -0.069236 -0.030400   

            ERP         0         1  ...        20        21        22  \
MYCT  -0.288396 -0.021050 -0.145286  ... -0.014374 -0.169784 -0.147085   
MMIN   0.819292 -0.046805  0.573734  ... -0.042217  0.204346  0.049745   
MMAX   0.901202 -0.034354  0.463073  ... -0.046208  0.164854 -0.041235   
CACH   0.648620  0.394822  0.165822  ... -0.043120  0.232867  0.043171   
CHMIN  0.610580  0.115238  0.269371  ...  0.033664  0.045837  0.008503   
CHMAX  0.592156  0.293369  0.126860  ...  0.293369 -0.058457 -0.053075   
PRP    0.966472  0.039922  0.410805  ... -0.032681  0.140474 -0.067921   
ERP    1.000000  0.044763  0.463511  ... -0.029790  0.122437 -0.024290   
0      0.044763  1.000000 -0.014709  ... -0.004808 -0.021926 -0.017857   
1      0.463511 -0.014709  1.000000  ... -0.014709 -0.067082 -0.054632   
2     -0.048279 -0.006816 -0.020851  ... -0.006816 -0.031083 -0.025315   
3     -0.003712 -0.006816 -0.020851  ... 

In [14]:
y = df['ERP']

In [15]:
x = df.drop(['ERP','PRP','Vendor name','Model name'],axis=1)

In [16]:
y.head()

0    199
1    253
2    253
3    253
4    132
Name: ERP, dtype: int64

In [17]:
x.head()

MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX    0    1    2    3  ...   20   21  \
0   125   256   6000   256     16    128  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1    29  8000  32000    32      8     32  0.0  1.0  0.0  0.0  ...  0.0  0.0   
2    29  8000  32000    32      8     32  0.0  1.0  0.0  0.0  ...  0.0  0.0   
3    29  8000  32000    32      8     32  0.0  1.0  0.0  0.0  ...  0.0  0.0   
4    29  8000  16000    32      8     16  0.0  1.0  0.0  0.0  ...  0.0  0.0   

    22   23   24   25   26   27   28   29  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 36 columns]

In [18]:
x = x.to_numpy()

In [19]:
y = y.to_numpy()

In [20]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
w = reg.coef_

In [22]:
w

array([ 7.14227831e-02,  1.73667215e-02,  5.50390047e-03,  6.43157128e-01,
       -1.52144498e+00,  1.58663686e+00, -1.20152953e+02, -1.48239022e+00,
        2.84413532e+01, -1.09132852e+01,  1.65327405e+01, -2.25179136e+01,
        3.36762519e+01,  2.26853409e+01,  1.09633351e+01,  1.47719779e+01,
        2.27795977e+01, -5.80161222e+00,  4.67541141e+01, -4.14901873e+01,
        1.18964838e+00, -2.40890874e+01,  1.63839660e+01, -6.93746550e+00,
        8.75855108e-01,  1.39006691e+01, -1.28899937e+02, -1.47169131e+01,
        4.43247471e-01,  2.71635048e+01,  2.55616542e+01,  2.44172510e+01,
       -2.38837401e+00,  5.21606241e+01,  4.77628050e+00,  1.59127070e+01])

In [23]:
b = reg.intercept_

In [24]:
y_ = reg.predict(x)

In [25]:
y_

array([ 1.99000000e+02,  3.04190504e+02,  3.04190504e+02,  3.04190504e+02,
        1.90741907e+02,  3.24557264e+02,  4.51105207e+02,  4.51105207e+02,
        6.27230022e+02,  9.72688882e+02,  2.19019170e+01,  2.50980830e+01,
        5.44747906e+01,  1.32525209e+02, -2.28192644e+01,  1.01819264e+02,
       -3.82621170e+01, -6.40972838e+00, -3.67897695e+01,  2.09754412e+02,
        2.09465530e+01,  2.91432750e+01,  8.35404746e+01,  9.50768999e+01,
        3.86572818e+01,  1.16033978e+01,  3.13604010e+01,  1.26614175e+01,
        3.12883729e+01,  2.84291290e+01,  8.33562564e+01,  8.33562564e+01,
        8.61940190e+01,  8.61940190e+01,  1.89859282e+02,  1.90430664e+02,
       -2.64428057e+01, -5.16500719e+00,  3.42173162e+01,  3.51410862e+00,
        2.55297105e+01,  8.69276357e+01,  8.85142726e+01,  8.85142726e+01,
        5.73096555e+01,  3.52940536e+01,  1.89058384e+01,  4.69370467e+01,
        2.88958003e+01,  2.76576054e+01,  5.29019614e+01,  1.76556182e+01,
        8.10980948e+01,  

In [26]:
y

array([ 199,  253,  253,  253,  132,  290,  381,  381,  749, 1238,   23,
         24,   70,  117,   15,   64,   23,   29,   22,  124,   35,   39,
         40,   45,   28,   21,   28,   22,   28,   27,  102,  102,   74,
         74,  138,  136,   23,   29,   44,   30,   41,   74,   74,   74,
         54,   41,   18,   28,   36,   38,   34,   19,   72,   36,   30,
         56,   42,   34,   34,   34,   34,   34,   19,   75,  113,  157,
         18,   20,   28,   33,   47,   54,   20,   23,   25,   52,   27,
         50,   18,   53,   23,   30,   73,   20,   25,   28,   29,   32,
        175,   57,  181,  181,   32,   82,  171,  361,  350,  220,  113,
         15,   21,   35,   18,   20,   20,   28,   45,   18,   17,   26,
         28,   28,   31,   31,   42,   76,   76,   26,   59,   65,  101,
        116,   18,   20,   20,   30,   44,   44,   82,   82,  128,   37,
         46,   46,   80,   88,   88,   33,   46,   29,   53,   53,   41,
         86,   95,  107,  117,  119,  120,   48,  1

In [27]:
reg.score(x,y)

0.929226077788117

In [28]:
x

array([[1.25e+02, 2.56e+02, 6.00e+03, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [2.90e+01, 8.00e+03, 3.20e+04, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [2.90e+01, 8.00e+03, 3.20e+04, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       ...,
       [1.25e+02, 2.00e+03, 8.00e+03, ..., 0.00e+00, 1.00e+00, 0.00e+00],
       [4.80e+02, 5.12e+02, 8.00e+03, ..., 0.00e+00, 0.00e+00, 1.00e+00],
       [4.80e+02, 1.00e+03, 4.00e+03, ..., 0.00e+00, 0.00e+00, 1.00e+00]])

In [29]:
x[0]

array([1.25e+02, 2.56e+02, 6.00e+03, 2.56e+02, 1.60e+01, 1.28e+02,
       1.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00,
       0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00])

In [30]:
x.shape

(209, 36)

In [31]:
x[0].reshape(1,-1).shape

(1, 36)

In [32]:
reg.predict(x[0].reshape(1,-1))

array([199.])

In [33]:
y[0]

199